# Generated by Django 5.1.4 on 2024-12-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='burgers/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(choices=[('Street', 'Street Burger'), ('Cheese', 'Cheese Burger'), ('Veggie', 'Veggie Burger'), ('BBQ', 'BBQ Burger'), ('Mushroom', 'Mushroom Burger')], max_length=50)),
            ],
        ),
    ]
